/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package quiz.app;

import java.sql.*;

/**
 *
 * @author user
 */
public class AddQuestion extends javax.swing.JPanel {

	/**
	 * Creates new form AddQuestion
	 */

  private javax.swing.JTextField question_field;
  private javax.swing.JTextField field1;
  private javax.swing.JTextField field2;
  private javax.swing.JTextField field3;
  private javax.swing.JTextField field4;

  private javax.swing.JCheckBox option1;
  private javax.swing.JCheckBox option2;
  private javax.swing.JCheckBox option3;
  private javax.swing.JCheckBox option4;

  private javax.swing.JButton addButton;
  private javax.swing.JButton doneButton;

	public AddQuestion() {
		  initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                question_field = new javax.swing.JTextField();
                option1 = new javax.swing.JCheckBox();
                option2 = new javax.swing.JCheckBox();
                option3 = new javax.swing.JCheckBox();
                option4 = new javax.swing.JCheckBox();
                field2 = new javax.swing.JTextField();
                field1 = new javax.swing.JTextField();
                field3 = new javax.swing.JTextField();
                field4 = new javax.swing.JTextField();
                addButton = new javax.swing.JButton();
                doneButton = new javax.swing.JButton();

                javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
                javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
                javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
                javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
                

                jLabel1.setText("jLabel1");

                setBackground(new java.awt.Color(255, 255, 255));

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("Add Question");
                jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

                question_field.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                question_fieldActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(127, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(question_field, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(127, 127, 127))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(264, 264, 264))))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(question_field, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(12, Short.MAX_VALUE))
                );

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                option2.setBackground(new java.awt.Color(255, 255, 255));
                option2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                option3.setBackground(new java.awt.Color(255, 255, 255));
                option3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                option4.setBackground(new java.awt.Color(255, 255, 255));
                option4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                option4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                option4ActionPerformed(evt);
                        }
                });

                option1.setBackground(new java.awt.Color(255, 255, 255));
                option1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                option1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                option1ActionPerformed(evt);
                        }
                });

                field4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                field4ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(option4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                        .addComponent(option1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(option2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(option3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(field4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                                .addComponent(field2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(field1))
                                        .addComponent(field3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(option1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                        .addComponent(field1))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(option2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                        .addComponent(field2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(option3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                        .addComponent(field3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(field4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                        .addComponent(option4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(81, Short.MAX_VALUE))
                );

                addButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                addButton.setText("Add");
                addButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
                addButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            addButtonActionPerformed(evt);
                        }
                });

                doneButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                doneButton.setText("Done");
                doneButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
                doneButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            doneButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(61, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(doneButton, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(108, 108, 108)
                                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(76, 76, 76)
                                                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(65, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void question_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question_fieldActionPerformed
                // TODO add your handling code here:

        }//GEN-LAST:event_question_fieldActionPerformed

        private void option1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_option1ActionPerformed

        private void option4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_option4ActionPerformed

        private void field4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field4ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_field4ActionPerformed

        private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
                // TODO add your handling code here:
            Utils.changePane(new Start());

          // check if question exists already

        }//GEN-LAST:event_addButtonActionPerformed

        private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
                // TODO add your handling code here:
            try {
                    Statement st = Utils.connection.createStatement();
                    String question = question_field.getText();

                    // check if question exists already
                    ResultSet rs = st.executeQuery(String.format("SELECT COUNT(Question) FROM %s.Questions WHERE Question = '%s'", Utils.databaseName, question));
                    System.out.println("got question id");
                    rs.next();
                    int questionID = rs.getInt(1);
                    if (questionID == 0) {
                        // insert the question into bank
                        st.execute(String.format("INSERT INTO %s.Questions (ID, Question) VALUES (null, '%s')", Utils.databaseName, question));
                    }
                    // get the question id
                    rs = st.executeQuery(String.format("SELECT ID from %s.Questions where Question = '%s'", Utils.databaseName, question));
                    rs.next();
                    questionID = rs.getInt(1);
                    System.out.println("Question ID: " + questionID);

                    // get quiz code id
                    rs = st.executeQuery(String.format("SELECT ID FROM %s.Codes WHERE CODE = '%s'", Utils.databaseName, Utils.quizCode));
                    rs.next();
                    int quizCodeID = rs.getInt(1);
                    boolean options[] ={ option1.isSelected(), option2.isSelected(), option3.isSelected(), option4.isSelected() };
                    String fields[] = { field1.getText(), field2.getText(), field3.getText(), field4.getText() };

                    // add options to database
                    for (int i=0; i<4; i++) {
                        st.execute(String.format("INSERT INTO %s.`Options` (`option`, QuestionID, QuizCode, isCorrect) VALUES('%s', %d, %d, %b);", Utils.databaseName, fields[i], questionID, quizCodeID, options[i]));
                    }

                    Utils.connection.commit();
                    Utils.PopUp("Question Added");
                } catch (Exception e) {
                    System.out.println(e);
                    try {
                        Utils.connection.rollback();
                    } catch (Exception e2) {}
                }

                // clear all fields
                question_field.setText("");
                option1.setSelected(false);
                option2.setSelected(false);
                option3.setSelected(false);
                option4.setSelected(false);
                field1.setText("");
                field2.setText("");
                field3.setText("");
                field4.setText("");
        }//GEN-LAST:event_doneButtonActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        // End of variables declaration//GEN-END:variables
}
