/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package quiz.app;

import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.sql.*;

/**
 *
 * @author user
 */
public class JoinQuiz extends javax.swing.JPanel {

    /**
     * Creates new form AddQuestion
     */
    public JoinQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel main_panel = new javax.swing.JPanel();
        javax.swing.JPanel organisation_panel = new javax.swing.JPanel();
        javax.swing.JLabel title_label = new javax.swing.JLabel();
        javax.swing.JLabel organisation_label = new javax.swing.JLabel();
        javax.swing.JLabel email_label = new javax.swing.JLabel();
        javax.swing.JTextField name_field = new javax.swing.JTextField();
        javax.swing.JLabel name_label1 = new javax.swing.JLabel();
        javax.swing.JTextField email_field = new javax.swing.JTextField();
        javax.swing.JButton join_button = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());
        setBorder(new EmptyBorder(new Insets(20,5,20,10)));
        setBackground(new Color(255, 255, 255));
        setPreferredSize(new Dimension(1001, 601));

        main_panel.setBackground(new java.awt.Color(255, 255, 255));

        organisation_panel.setBackground(new java.awt.Color(255, 255, 255));
        organisation_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/QuizApplication",
                    "vaibhavj",
                    "rockatale"
            );
            connection.setAutoCommit(false);

            title_label.setBackground(new java.awt.Color(255, 255, 255));
            title_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
            title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            title_label.setText("Title");

            organisation_label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
            organisation_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            organisation_label.setText("Organisation Name");

            Statement st = connection.createStatement();
            st.executeQuery("SELECT Organisation,Title FROM Code");

        } catch (Exception e ) {
            System.out.println(e);
        }

        javax.swing.GroupLayout organisation_panelLayout = new javax.swing.GroupLayout(organisation_panel);
        organisation_panel.setLayout(organisation_panelLayout);
        organisation_panelLayout.setHorizontalGroup(
                organisation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(organisation_panelLayout.createSequentialGroup()
                                .addContainerGap(30, Short.MAX_VALUE)
                                .addGroup(organisation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(organisation_label, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        organisation_panelLayout.setVerticalGroup(
                organisation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(organisation_panelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(organisation_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        email_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email_label.setText("E-Mail");

        name_label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_label1.setText("Name");

        join_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        join_button.setText("Join Quiz");

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
                main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(main_panelLayout.createSequentialGroup()
                                .addContainerGap(11, Short.MAX_VALUE)
                                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panelLayout.createSequentialGroup()
                                                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panelLayout.createSequentialGroup()
                                                                .addGap(166, 166, 166)
                                                                .addComponent(join_button, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(268, 268, 268))
                                                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(main_panelLayout.createSequentialGroup()
                                                                        .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(email_field))
                                                                .addGroup(main_panelLayout.createSequentialGroup()
                                                                        .addComponent(name_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(143, 143, 143))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panelLayout.createSequentialGroup()
                                                .addComponent(organisation_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(17, 17, 17))))
        );
        main_panelLayout.setVerticalGroup(
                main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(main_panelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(organisation_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(name_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(name_field, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(email_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addComponent(join_button, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173))
        );

        add(main_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
