/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package quiz.app;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author user
 */
public class Start extends javax.swing.JPanel {

    /**
     * Creates new form Start
     */

    private java.awt.TextField Name_Field;
    private java.awt.TextField Email_Field;
    private java.awt.TextField Organisation_Field;
    private java.awt.TextField title_field;
    private java.awt.TextField quiz_code_field;
    private javax.swing.JButton createQuizButton;
    private javax.swing.JButton joinQuizButton;


    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name_Field = new java.awt.TextField();
        quiz_code_field = new java.awt.TextField();
        Organisation_Field = new java.awt.TextField();
        Email_Field = new java.awt.TextField();
        title_field = new java.awt.TextField();
        joinQuizButton = new javax.swing.JButton();
        createQuizButton = new javax.swing.JButton();

        joinQuizButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                joinQuizButtonActionPerformed(actionEvent);
            }
        });

        createQuizButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                createQuizButtonActionPerformed(actionEvent);
            }
        });

        javax.swing.JPanel start = new javax.swing.JPanel();
        javax.swing.JPanel main_panel = new javax.swing.JPanel();
        javax.swing.JPanel create_quiz_panel2 = new javax.swing.JPanel();
        javax.swing.JLabel Email_label = new javax.swing.JLabel();
        javax.swing.JLabel Name_label2 = new javax.swing.JLabel();
        javax.swing.JLabel title_label = new javax.swing.JLabel();
        javax.swing.JLabel organisation_label = new javax.swing.JLabel();
        java.awt.Label or = new java.awt.Label();
        javax.swing.JPanel join_quiz_panel = new javax.swing.JPanel();
        javax.swing.JLabel quiz_code_label = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout(1, 1));

        start.setBackground(new java.awt.Color(255, 255, 255));
        start.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        start.setName("home"); // NOI18N

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        main_panel.setPreferredSize(new java.awt.Dimension(828, 510));

        create_quiz_panel2.setBackground(new java.awt.Color(255, 255, 255));

        Name_Field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Name_Field.setName("Name"); // NOI18N

        Email_Field.setName("Email_Field"); // NOI18N

        Organisation_Field.setName("Organisation_Field"); // NOI18N

        Email_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Email_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Email_label.setText("Email");

        Name_label2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Name_label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name_label2.setText("Name");

        title_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_label.setText("Title");

        organisation_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        organisation_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        organisation_label.setText("Organisation");

        title_field.setName("Organisation_Field"); // NOI18N

        createQuizButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createQuizButton.setText("Create Quiz");
        createQuizButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout create_quiz_panel2Layout = new javax.swing.GroupLayout(create_quiz_panel2);
        create_quiz_panel2.setLayout(create_quiz_panel2Layout);
        create_quiz_panel2Layout.setHorizontalGroup(
                create_quiz_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(create_quiz_panel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(create_quiz_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(createQuizButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, create_quiz_panel2Layout.createSequentialGroup()
                                                .addGroup(create_quiz_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(title_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Name_label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Email_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(organisation_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(27, 27, 27)
                                                .addGroup(create_quiz_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(Email_Field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                                        .addComponent(Name_Field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Organisation_Field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(title_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        create_quiz_panel2Layout.setVerticalGroup(
                create_quiz_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(create_quiz_panel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(create_quiz_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Name_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(create_quiz_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Email_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(create_quiz_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Organisation_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(organisation_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(create_quiz_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(title_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(createQuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(44, Short.MAX_VALUE))
        );

        or.setAlignment(java.awt.Label.CENTER);
        or.setEnabled(false);
        or.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        or.setName("or"); // NOI18N
        or.setText("OR");

        join_quiz_panel.setBackground(new java.awt.Color(255, 255, 255));
        join_quiz_panel.setName("join_quiz_panel"); // NOI18N

        quiz_code_field.setName("Quiz_code_field"); // NOI18N

        quiz_code_label.setBackground(new java.awt.Color(255, 255, 255));
        quiz_code_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        quiz_code_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quiz_code_label.setText("Quiz Code");

        joinQuizButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        joinQuizButton.setText("Join Quiz");
        joinQuizButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout join_quiz_panelLayout = new javax.swing.GroupLayout(join_quiz_panel);
        join_quiz_panel.setLayout(join_quiz_panelLayout);
        join_quiz_panelLayout.setHorizontalGroup(
                join_quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, join_quiz_panelLayout.createSequentialGroup()
                                .addContainerGap(23, Short.MAX_VALUE)
                                .addGroup(join_quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(joinQuizButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(quiz_code_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(quiz_code_label, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                                .addGap(14, 14, 14))
        );
        join_quiz_panelLayout.setVerticalGroup(
                join_quiz_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(join_quiz_panelLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(quiz_code_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(quiz_code_field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(joinQuizButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quiz");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
                main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(main_panelLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(create_quiz_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(or, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(join_quiz_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panelLayout.createSequentialGroup()
                                .addContainerGap(233, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(238, 238, 238))
        );
        main_panelLayout.setVerticalGroup(
                main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(main_panelLayout.createSequentialGroup()
                                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(main_panelLayout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(main_panelLayout.createSequentialGroup()
                                                                .addGap(149, 149, 149)
                                                                .addComponent(or, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(main_panelLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(create_quiz_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(join_quiz_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout startLayout = new javax.swing.GroupLayout(start);
        start.setLayout(startLayout);
        startLayout.setHorizontalGroup(
                startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startLayout.createSequentialGroup()
                                .addContainerGap(34, Short.MAX_VALUE)
                                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(35, Short.MAX_VALUE))
        );
        startLayout.setVerticalGroup(
                startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startLayout.createSequentialGroup()
                                .addContainerGap(43, Short.MAX_VALUE)
                                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(44, Short.MAX_VALUE))
        );

        add(start, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void createQuizButtonActionPerformed(ActionEvent ae) {
        String code = Utils.genCode(6);
        String[] name = Name_Field.getText().split(" ", 2);
        String email = Email_Field.getText();
        String organisation = Organisation_Field.getText();
        String title = title_field.getText();
        if (name.length == 0 || email.length() == 0 || organisation.length() == 0 || title.length() == 0) {
            Utils.PopUp("Invalid Data Entered.");
            return;
        }

        String fname = name[0];
        String lname = (name.length > 1) ? name[1] : "";
        try {
            java.sql.Statement st = Utils.connection.createStatement();
            String query;

            // check if user exists
            query = String.format("SELECT COUNT(ID) " +
                    String.format("FROM %s.Users ", Utils.databaseName) +
                    "WHERE EMAIL='%s'", email);

            java.sql.ResultSet rs = st.executeQuery(query);
            rs.next();
            int cnt = rs.getInt(1);

            // add if not exists
            if (cnt == 0) {
                query = String.format("INSERT INTO %s.Users " +
                        "(Organisation, isActive, Email, FName, LName) VALUES " +
                        "('%s', true, '%s', '%s', '%s')", Utils.databaseName, organisation, email, fname, lname);
                st.execute(query);
            }

            // get id of this user
            query = String.format("SELECT ID FROM %s.Users WHERE Email='%s'", Utils.databaseName, email);
            rs = st.executeQuery(query);
            rs.next();
            int id = rs.getInt(1);

            // add quiz code
            query = String.format("INSERT INTO %s.Codes (Code, createdBy, Title) " +
                    "VALUES('%s', %d, '%s')", Utils.databaseName, code, id, title);
            st.execute(query);
            Utils.connection.commit();
            st.close();

            System.out.println("Code: " + code);
            Utils.PopUp(String.format("Your code is %s", code));
            Utils.changePane(new AddQuestion());

        } catch (Exception e) {
            System.out.println(e);
            try {
                Utils.connection.rollback();
            } catch(Exception e1) {
                System.out.println(e1);
            }
        }
    }
    private void joinQuizButtonActionPerformed(ActionEvent ae) {
        String code = quiz_code_field.getText();
        try {
            java.sql.Statement st = Utils.connection.createStatement();
            java.sql.ResultSet rs = st.executeQuery(String.format("SELECT COUNT(Code) FROM %s.Codes WHERE Code = '%s'", Utils.databaseName, code));
            rs.next();
            int n = rs.getInt(1);
            System.out.println(n);
            if (n == 0) throw new Exception();

            Utils.quizCode = code;

            Utils.changePane(new JoinQuiz());

        } catch(Exception e) {
            Utils.PopUp("Invalid Quiz Code");
            System.out.println("Invalid Quiz Code");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
